
#include<POKEMON_.cpp>
/* It contains the definitions and assaciated numbers of all 4 pokemons and
   their attacks                       */

/**/
/**/



#include<ELLIPSE_.cpp>
/* It is the program that prints an ellipse in the middle and user_desired
   number of ellipses on the sides      */

#include<LINE_DAN.cpp>
// A line completes a rotation on the screen without clearing the previous
// line

#include<MOV_ELP1.cpp>
/* Two ellipses move in the screen      */


#include<G_BORDER.cpp>
/* Its a border printing program        */


#include<WELCOME_.cpp>
/* It prints welcome message on screen  */
