#include<WEEP_BEL.cpp>
/* contains...
   @ the class `weepinbell_' that contains the associated numbers of
	the pokemon - weepinbell itself and also its grass_attacks.
   @  the definitions of animations of its attacks,
   @  the definition of the pokemon - picture              */

#include<PIKACHU_.cpp>
/* contains...
   @ the class `pikachu_' that contains the associated numbers of
	the pokemon - pikachu itself and also its electric_attacks.
   @  the definitions of animations of its attacks,
   @  the definition of the pokemon - picture              */

#include<GOLDEEN_.cpp>
/* contains...
   @ the class `goldeen_' that contains the associated numbers of
	the pokemon - goldeen itself and also its water_attacks.
   @  the definitions of animations of its attacks,
   @  the definition of the pokemon - picture              */

#include<TORCHIC_.cpp>
/* contains...
   @ the class `torchic_' that contains the associated numbers of
	the pokemon - torchic itself and also its fire_attacks.
   @  the definitions of animations of its attacks,
   @  the definition of the pokemon - picture              */
